### ISSUE TITLE
As a consumer of the API, I want to have a login mechanism with different groups, roles and users

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/beacon-suedtirol-api#41]
- [x] Create the database backend things (tables, ...)
- [x] Add group and role information to the JWT token
- [x] Login and use the existing API with the new JWT tokens

**Comment by davidebz** [comment]
We have preferred to remember the user id information only and read from tables the role/group only when required. This allow to have real-time checking about user role/group and not only the role/group at login
