### ISSUE TITLE
As an API consumer I want to assign beacons to groups

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/beacon-suedtirol-api#42]

**Comment by davidebz** [comment]
Which role(s) can assign a beacon to a group?

**Comment by davidebz** [comment]
What happens in case of a change of group? Which rights should we check (old and new group)

**Comment by davidebz** [comment]
What happens in case of a change of group? Which rights should we check (old and new group): ONLY ADMIN

**Comment by davidebz** [comment]
Which role(s) can assign a beacon to a group: using method /v1/admin/beacons/createByOrder 

user ADMIN: optionally a group_id
user MANAGER: required group_id parameter. check that the logged user is MANAGER of this group_id
