### ISSUE TITLE
As a Beacon admin, I want to see the correct beacon battery, so that I can take measures if they are low on charging power.

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/beacon-suedtirol-api#55]
Currently there is no working app which transmits the Beacon battery state to the admin interface(maybe the admin app which nobody really uses). Since we are close on releaseing the first version of Beacon Suedtirol guide, it should be working there but in the test version currently the beacon api says authentication fails.

**Comment by bertolla** [comment]
Since nobody has the right credentials i did it this way:
- Took my beacon admin encrypted password from db and replaced it in the beacon api with the current encrypted password
- Tested the patch request with curl and it worked :tada: 
- replaced credentials in Jenkins
- replaced credentials in password server
- changed my password

**Comment by bertolla** [comment]
Please test this by using the curl command I send you through ms teams and use the credentials found on password server beaconprodtrusteduser(dont remember exactly how its called).

**Comment by Piiit** [comment]
@bertolla Works, but I had to modify your curl command and add `Content-Type` for json... 

```
curl -w '\n' --user 'admin:blablabla' -H "Content-Type: application/json" -i -X PATCH -d '{"batteryLevel": 100}' 'https://api.beacon.bz.it/v1/trusted/beacons/lLiun0/batteryLevel'
```
Response:
```
HTTP/1.1 200 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Mon, 23 Mar 2020 15:24:33 GMT
Expires: 0
Pragma: no-cache
Server: Apache/2.4.39 (Amazon) OpenSSL/1.0.2k-fips
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
transfer-encoding: chunked
Connection: keep-alive

{"id":"lLiun0","manufacturer":"KONTAKT_IO","manufacturerId":"otW9ma","name":"NOI0135#lLiun0","description":"Kabelbinder, Decke ","lat":46.47836,"lng":11.331851,"locationType":"INDOOR","locationDescription":"","lastSeen":1583749143000,"iBeacon":true,"telemetry":false,"eddystoneUid":true,"eddystoneUrl":true,"eddystoneTlm":true,"eddystoneEid":false,"eddystoneEtlm":false,"uuid":"6a84c716-0f2a-1ce9-f210-6a63bd873dd9","major":8147,"minor":18263,"url":"https://bs.bz.it/lLiun0","namespace":"6a84c7166a63bd873dd9","instanceId":"675bd8ff05de","interval":350,"txPower":3,"batteryLevel":100,"pendingConfiguration":null,"internalName":"NOI0135#lLiun0","status":"OK"}
```
